### ISSUE TITLE
Release 3.3.0 isn't published 

### ISSUE THREAD

**Issue by francismariano** [ajalt/colormath#36]
Are there a milestone to publish the 3.3.0 release version??

**Comment by ajalt** [comment]
Sorry for the delay. I'm still trying to find a solution to the gradle task dependency bugs that are preventing the publication from succeeding. The workarounds folks have suggested haven't worked for me, so I'm still looking for a solution.

**Comment by JakeWharton** [comment]
What's the stacktrace you're seeing?

**Comment by ajalt** [comment]
I'm just running into the usual bug where the publication task isn't declaring its dependency on the signing task. I tried the [workaround][1] you suggested on the kotlinlang slack, but that caused signatures not to be generated at all for some of the targets. 

I also tried switching over to the vanniktech publishing plugin, since it seems to have a workaround for that problem, but then I ran into the similar [issue with dokka][2].

I'm sure I'm doing something wrong, but I haven't figured out what yet

[1]: https://github.com/ajalt/colormath/blob/195b1d1e3b59eaf9d26a412bb4052ef46ccae3c3/gradle/publish.gradle.kts#L78 
[2]: https://github.com/Kotlin/dokka/issues/1833

**Comment by ajalt** [comment]
sorry this took so long, but I finally got everything working, so 3.3.0 should be available on maven central shortly
