### ISSUE TITLE
OKLCH conversion issues

### ISSUE THREAD

**Issue by sebj** [ajalt/colormath#40]
I've run into two issues converting OKLCH colours to both Display P3 and sRGB. I'm not totally sure if these are user-error, or a library issue, but I was hoping you'd have more insight.

1. Conversion to Display P3 and sRGB produces out-of-gamut colours unnecessarily:
```kotlin
val color = Oklch(l=1.0f, c=0.0f, h=220.0f, alpha=1.0f)
color.convertTo(RGBColorSpaces.DisplayP3) // Out of gamut: RGB(r=1.0001497, g=0.999987, b=0.9996814, alpha=1.0, space=Display P3)
color.convertTo(RGBColorSpaces.SRGB) // Out of gamut: RGB(r=1.0, g=1.0, b=1.0, alpha=1.0, space=sRGB)
```

Viewing this colour on web, it seems to be in-gamut for both P3 and sRGB color spaces: https://oklch.com/#100,0,220,100

2. Conversion to sRGB produces out-of-gamut colour instead of mapping into that gamut

```kotlin
val color = Oklch(l=0.6654f, c=0.151f, h=220.0f, alpha=1.0f)
color.convertTo(RGBColorSpaces.DisplayP3) // In-gamut: RGB(r=0.13223152, g=0.64369315, b=0.8096382, alpha=1.0, space=Display P3)
color.convertTo(RGBColorSpaces.SRGB) // Out of gamut: RGB(r=-0.83220994, g=0.65525836, b=0.82784724, alpha=1.0, space=sRGB)
```

I'm not sure if I'm misunderstanding the behaviour of `convertTo` here, but I would have expected it to map the colour into an in-gamut sRGB colour, like the fallback produced here: https://oklch.com/#66.54,0.151,220,100

**Comment by ajalt** [comment]
Colormath deliberately doesn't truncate any values automatically, since that would lose informatation, espectially for intermediate calculations. If you want, you can [clamp][1] your RGB values after conversion. I haven't implemented any [advanced gamut mapping][2] yet, but I'd be open to a PR for that. 

[1]: https://ajalt.github.io/colormath/api/colormath/com.github.ajalt.colormath.model/-r-g-b/clamp.html?query=fun%20clamp():%20RGB
[2]: https://bottosson.github.io/posts/gamutclipping/
