### ISSUE TITLE
Dokka API docs are outdated

### ISSUE THREAD

**Issue by EdricChan03** [ajalt/colormath#44]
Nice library! I've noticed that the docs were last generated [2 years ago](https://github.com/ajalt/colormath/commits/gh-pages/) - are there plans to update it?

### Other comments

* The docs could also do with some fixing - for example, the following API looks ambiguous (there are no links for either class, so it's a bit confusing to determine from this alone as to which `Color` is which):

![image](https://github.com/ajalt/colormath/assets/20047125/5cb225b1-81f9-419a-8542-ea055aae55e8)

* There should be a way to link to the corresponding source code. Dokka can handle this by specifying the relevant config :P

* It also appears that the API docs don't have a combined docs page (for example, the [Kord library for creating Discord bots in Kotlin](https://dokka.kord.dev/) has one)

**Comment by ajalt** [comment]
Thanks for the heads up, I just pushed a new version of the docs.

- I added an external documentation link, but Dokka seems to not be able to there being a class named `Color` from two different packages in the same signature. I could get it to link to either the android `Color` or the colormath `Color`, but not both. 
- I tried to set up multimodule docs, but dokka crashed with an internal error. 

If you know how to get either of those working, I'd welcome a PR, but otherwise I'll leave it alone.
